name: Build Plugins

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src/Artemis.Plugins.Modules.Chrome/Artemis.Plugins.Modules.Chrome.sln

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Artemis.Plugins.Modules.Chrome
          path: src/Artemis.Plugins.Modules.Chrome/bin/x64/Release/net7.0/publish
          if-no-files-found: error
