name: Build Plugins

on:
  push:
  workflow_dispatch:
    inputs:
      run_build:
        description: "Run build"
        required: true
        type: boolean
      run_actionlint:
        description: "Run actionlint"
        required: true
        type: boolean

jobs:
  changes:
    runs-on: ubuntu-latest
    name: Gather changed files
    if: ${{ inputs == null }}
    outputs:
      run_build: ${{ steps.changes.outputs.run_build }}
      run_actionlint: ${{ steps.changes.outputs.run_actionlint }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout code from the repo

      - name: Get changed files
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            run_build:
              - 'src/**'
            run_actionlint:
              - '.github/workflows/**'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.run_build == 'true' || inputs.run_build }}

    steps:
      - name: Setup .NET 7.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Clone
        uses: actions/checkout@v2

      - name: Build
        run: dotnet publish -c Release src/Artemis.Plugins.Modules.Chrome.sln

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Artemis.Plugins.Modules.Chrome
          path: src/Artemis.Plugins.Modules.Chrome/bin/Release/net7.0/publish
          if-no-files-found: error

  actionlint:
    name: Check workflow files
    needs: changes
    runs-on: ubuntu-latest
    if: ${{ needs.changes.outputs.run_actionlint == 'true' || inputs.run_actionlint }}
    steps:
      - uses: actions/checkout@v3
        name: Checkout code from the repo
      - name: Download actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.6.21
        shell: bash
      - name: Check workflow files
        run: ./actionlint -color
        shell: bash
